config/routes.rb
Rails.application.routes.draw do

  # get 'sessions#login'
  #
  # get 'sessions#home'
  #
  # get 'sessions#profile'
  #
  # get 'sessions#setting'
  #
  # get 'users#new'


resources :articles do

 resources :comments
end

resources :reply
post '/reply/new', to: 'reply#create'


post '/users', to: 'users#create'

 # get '/users/new', to: 'users#new'

get 'login', :to => 'sessions#login'
get 'signup', :to => 'users#new'
get 'login', :to => 'sessions#login'
post 'logout', :to => 'sessions#logout'
get 'home', :to => 'sessions#home'
get 'profile', :to => 'sessions#profile'
post 'login' , :to => 'sessions#login_attempt'


# match "setting", :to => "sessions#setting"



 # resources :users

# resources :sessions
 
 root 'welcome#home'

get 'welcomeshow', :to => 'welcome#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
					length: { minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  has_many :replies
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  EMAIL_REGEX = /\A(\S+)@(.+)\.(\S+)\z/
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
   validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create


def encrypt_password
  if password.present?
  self.salt = BCrypt::Engine.generate_salt
  self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  end
end

  def clear_password
    self.password = nil
  end


  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end
  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end




  before_save :encrypt_password
  after_save :clear_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protected
  def authenticate_user
    if session[:user_id]
      # set current user object to @current_user object variable
      @current_user = User.find session[:user_id]

      return true
    else
      redirect_to(:controller => 'sessions', :action => 'login')
      return false
    end
  end
  def save_login_state
    if session[:user_id]
      redirect_to(:controller => 'sessions', :action => 'home')
      return false
    else
      return true
    end
  end


  before_action :save_login_state, :only => [:login, :login_attempt]

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "adi", password: "adi", except: [:index]

  def index
    @articles = Article.all
  end


	def new
    @article= Article.new
  end

	def edit
	@article=Article.find(params[:id])
	end

	
	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		if(@article.save)
			redirect_to @article
		else
		render 'new'
		end	
	end


	def update
		@article = Article.find(params[:id])
 
  if @article.update(article_params)
			redirect_to @article
		else
		 render 'edit'
		end	
	end



	def show
		@article=Article.find(params[:id])
		@reply = Reply.new
	end



	def destroy
  		@article = Article.find(params[:id])
  		@article.destroy
 
  		redirect_to articles_path
	end


	private
  		def article_params
    		params.require(:article).permit(:title, :text)
  		end

	before_action :authenticate_user ,:only => [:index, :new, :show, :edit, :create, :update, :destroy]
  before_action :save_login_state, :only => [:login, :login_attempt]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create

     @article= Article.find(params[:article_id])
     @comment=@article.comments.create(comment_params)
	 redirect_to article_path(@article)

 end
  

 def destroy
     @article = Article.find(params[:article_id])
     @comment = @article.comments.find(params[:id])
     @comment.destroy
     redirect_to article_path(@article)
 end
 
 private
   def comment_params
      params.require(:comment).permit(:commenter, :body)
   end
end

app/controllers/reply_controller.rb
class ReplyController < ApplicationController

def new
@reply = Reply.new
end

  def create
byebug
    @reply= Reply.create(reply_params)

 redirect_to article_path( @reply)
  end

  def show
    @reply=Reply.find(params[:comment_id])
  end

def edit

end

  def update

  end

  def destroy

  end


private
def reply_params
  params.require(:reply).permit(:reply, :comment_id)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    # login form
  end

  def login_attempt

    authorized_user = User.authenticate(params[:username_or_email], params[:login_password])

if authorized_user
  session[:user_id] = authorized_user.id
  flash[:notice]="Welcome #{authorized_user.username}"
  redirect_to url_for(:controller => :articles, :action => :index)
else

  flash[:notice]="invalid username or password"
  flash[:color]="Invalid"
  render "login"


end
  end






  def home
  end

  def profile
  end

  def setting
  end





  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

   before_action :authenticate_user, :only => [:home, :profile, :setting, ]
   before_action :save_login_state, :only => [:login, :login_attempt]


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  @user = User.new
  end

  def create
  @user = User.new(user_params)
  if @user.save
    flash[:notice] = "You signed up successfully"
    flash[:color] = "Valid"
  else
    flash[:notice] = "Form is invalid"
    flash[:color] = "Invalid"
  end
  redirect_to root_path
  end



  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

   before_action :save_login_state, :only => [:new, :create]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def home
    @articles = Article.all
  end

  def show

    @article=Article.find(params[:format])
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<html>


<head>
<%= stylesheet_link_tag 'articles.css'%>

</head>

<body>

<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
   <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 <% author=@current_user.username %>
<% end %>


</body>
</html>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<html>





<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<%= link_to 'Back to Homepage', root_path %>

<%= link_to 'Logout', logout_path, method: :post %>
<br>
<br>
<!--<table>-->
  <!--<tr>-->
    <!--<th>Title</th>-->
    <!--<th>Text</th>-->
  <!--</tr>-->
  <!-- Blog entry -->
  <% @articles.each do |article| %>

      <div class="w3-card-4 w3-margin w3-white">

        <div class="w3-container">
          <h3><b>BLOG ENTRY</b></h3>
          <h5>Title:<%= article.title %> <br> Updated at:<span class="w3-opacity"><%= article.updated_at.strftime("%d-%m-%Y ") %></span></h5>
        </div>

        <div class="w3-container">

        <p>
         Text: <%= truncate(article.text, :length => 100) %>
        </p>



          <div class="w3-row">
            <div class="w3-col m8 s12">
              <!--show button-->
              <p><%= button_to 'Read More', article_path(article), :method => :get , :id => "myButton" %></p>

            </div>

            <div class="w3-col m8 s12">
              <p><%= link_to 'Edit', edit_article_path(article) %></p>
            </div>
            <div class="w3-col m8 s12">
              <p> <%= link_to 'Destroy', article_path(article),
               method: :delete,
              data: { confirm: 'Are you sure?' } %></p>
            </div>
          </div>
        </div>
      </div>


        </div>
      </div>

<% end %>


        <!---->
        <!--<tr>-->
      <!--<td><%#= article.title %></td>-->
      <!--<td><%#= article.text %></td>-->
      <!--<td></td>-->
      <!--<%#= button_to "New Post", { :action => "new" }, :method => :get %>-->

      <!--<td><%#= link_to 'Edit', edit_article_path(article) %></td>-->
      <%#= link_to 'Destroy', article_path(article),
#               method: :delete,
              data: { confirm: 'Are you sure?' } %>
    <!--</tr>-->

<!--</table>-->
</html><%#= button_to 'Show', article_path(article), :method => :get , :id => "myButton" %>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="w3-card-4 w3-margin w3-white">
        <div class="w3-margin-left">
         <br>
          <p>
          <strong>Title:</strong>
          <%= @article.title %>
        </p>

        <p>
          <strong>Text:</strong>
          <%= @article.text %>
        </p>
        </div>

    <div class="w3-card-4 w3-margin-left w3-margin-right">
       <div class="w3-margin-left"> <h2> Comments: </h2>
        <%= render @article.comments %>
         </div>
             <div class="w3-margin-left"><h2> Add a comment </h2>
              <%= render 'comments/form' %>
             </div>
      <div>
        <div class="w3-margin-left">
          <%= render 'reply/reply' %>
        </div>

        </div>
      </div>
    </div>



        <%= link_to 'Edit', edit_article_path(@article) %> |
        <%= link_to 'Back', articles_path %>
    </div>
    

app/views/comments/_comment.html.erb
<div>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>

</p>


<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

  <div class="w3-margin-left">
    <%= render 'reply/form', :locals => {:cmnt_id => comment.id} %>
  </div>

</div>

app/views/comments/_form.html.erb
<div class="w3-container w3-card-4 w3-gray w3-margin ">

<%= form_for([@article, @article.comments.build]) do |f| %>
  <div class="w3-margin-left w3-margin-bottom">
      <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
  </div>





</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reply/_form.html.erb
<div>
  <%= form_for @reply, url: new_reply_path do |r|%>
      <%= r.label :reply %><br>
      <%= r.text_field :reply %>
      <%= byebug %>
      <%= r.hidden_field :comment_id, :value => cmnt_id %>
      <%= r.submit%>
  <% end %>

</div>

app/views/reply/_reply.html.erb
<p>
  <strong>Reply:</strong>
  <%= @reply.reply %>
</p>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
<%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>

      <p>Username: <br><%= f.text_field :username %></p>
      <p>Email: <br><%= f.text_field :email %></p>
      <p>Password: <br><%= f.password_field :password %></p>
      <p>Confirm Password:<br> <%= f.password_field :password_confirmation %></p>
<%= f.submit %>
  <% end %>

  <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    <% end %>
  </ul>
</div>
      </div>

app/views/welcome/home.html.erb
<html>





<h1>Homepage</h1>
<%= link_to 'Login', login_path %>
<%= link_to 'SignUp', signup_path %>
<br>
<br>
<!--<table>-->
<!--<tr>-->
<!--<th>Title</th>-->
<!--<th>Text</th>-->
<!--</tr>-->
<!-- Blog entry -->
<% @articles.each do |article| %>

    <div class="w3-card-4 w3-margin w3-white">

      <div class="w3-container">
        <h3><b>BLOG ENTRY</b></h3>
        <h5>Title:<%= article.title %> <br> Updated at:<span class="w3-opacity"><%= article.updated_at.strftime("%d-%m-%Y ") %></span></h5>
      </div>

      <div class="w3-container">

        <p>
          Text: <%= truncate(article.text, :length => 100) %>
        </p>



        <div class="w3-row">
          <div class="w3-col m8 s12">
            <!--show button-->
            <p><%= button_to 'Read More', welcomeshow_path(article), :method => :get , :id => "myButton" %></p>

          </div>



        </div>
      </div>
    </div>


    </div>
    </div>

<% end %>


<!---->
<!--<tr>-->
<!--<td><%#= article.title %></td>-->
<!--<td><%#= article.text %></td>-->
<!--<td></td>-->
<!--<%#= button_to "New Post", { :action => "new" }, :method => :get %>-->

<!--<td><%#= link_to 'Edit', edit_article_path(article) %></td>-->
<%#= link_to 'Destroy', article_path(article),
#               method: :delete,
              data: { confirm: 'Are you sure?' } %>
<!--</tr>-->

<!--</table>-->





<%#= button_to 'Show', article_path(article), :method => :get , :id => "myButton" %>



</html>

app/views/welcome/index.html.erb
<big><marquee> <h1>hello , Rails !</h1> </marquee></big>

<%= link_to 'Old blog' , controller: 'articles'%>

<!DOCTYPE html>
<html>

<head>
  <style>
    .row {
      box-sizing: border-box;
      padding-left: 10px;
    }

    .col1, .col2, .col3 {
      left: 5px;
      border: 2px solid black;
      margin-bottom: 10px;
      display: inline-block;
      padding: 5px;
      width: 24%;
    }

    #bdy {
      border-width: 0px;
      padding: 0px;
      margin: 0px;
      font-size: 90%;
      background-color: #e7e7de
    }
  </style>
</head>


<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdn.rawgit.com/nnattawat/flip/master/dist/jquery.flip.min.js"></script>



<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
  body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey">

<!-- w3-content defines a container for fixed size centered content,
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">

  <!-- Header -->
  <header class="w3-container w3-center w3-padding-32">
    <h1><b>Aditya's BLOG</b></h1>
    <p>Welcome to the blog of <span class="w3-tag">Aditya</span></p>
  </header>




  <!-- Grid -->
  <div class="w3-row">

    <!-- Blog entries -->
    <div class="w3-col l8 s12">
      <!-- Blog entry -->

      <div id="card" class="w3-card-4 w3-margin w3-white">
        <div class="front">
          <%= image_tag("rss.jpg", :alt => "rss feed") %>
        </div>
        <div class="back">
          <%= image_tag("img3.jpg", :alt => "rss feed" , size: "800x800") %>
        </div>

        <%#= image_tag("rss.jpg", :alt => "rss feed" , id:'rsimg') %>
        <div class="w3-container">
          <h3><b></b></h3>
          <h5>Fly High <span class="w3-opacity">April 7, 2014</span></h5>
        </div>

        <div class="w3-container">
          <p>A piece of popcorn<br>
            escaped from the pan<br>
            and flew across the kitchen<br>
            like Superman</p>
          <div class="w3-row">
            <div class="w3-col m8 s12">
              <p><button class="w3-button w3-padding-large w3-white w3-border"><b>READ MORE »</b></button></p>
            </div>
            <div class="w3-col m4 w3-hide-small">
              <p><span class="w3-padding-large w3-right"><b>Comments  </b> <span class="w3-tag">0</span></span></p>
            </div>
          </div>
        </div>
      </div>
      <hr>

      <!-- Blog entry -->
      <div class="w3-card-4 w3-margin w3-white">

        <div class="w3-container">
          <h3><b>BLOG ENTRY</b></h3>
          <h5>Six must have accesories this monsoon <span class="w3-opacity">April 2, 2014</span></h5>
        </div>

        <div class="w3-container">
          <div>
            <%= image_tag("monsoon.jpg", :alt => "rss feed" , size: "759x432") %>

          </div>
          <p>* Raincoats: Raincourts are definitely making a come-back this season, with new patterns, colours and material to suit your style. From a balloon raincoat or rain poncho to a transparent one, a quick Google search can find you your perfect match!<br><br>

            * Shoes: Hate getting wet? Jelly flats, funky flip flops or bright and shiny gumboots can be your best friends this season.<br><br>

            * Bags: Try picking up a nylon or plastic tote bag to keep all your possessions safe and dry during the rains.<br><br>

            * Umbrellas: Yeah, we all have umbrellas, but do you have a stylist one? Get rid of those boring black ones and pick up a bright, colourful one, preferably with a beautiful design.<br><br>

            * Waterproof phone covers: An essential item today, phone covers can spruce up your style quotient and protect your phone from the rain.<br><br>

            * Scarves: Scarves are a fashion accessory that not only completes your outfit but also comes in handy during the rains. Lovely prints in a myriad colours and in different fabrics like cotton, mulmul and chiffon are easily accessible this season.<br><br>

            (Source: IANS)</p>
          <div class="w3-row">
            <div class="w3-col m8 s12">
              <p><button class="w3-button w3-padding-large w3-white w3-border"><b>READ MORE »</b></button></p>
            </div>
            <div class="w3-col m4 w3-hide-small">
              <p><span class="w3-padding-large w3-right"><b>Comments  </b> <span class="w3-badge">2</span></span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- END BLOG ENTRIES -->
    </div>

    <!-- Introduction menu -->
    <div class="w3-col l4">
      <!-- About Card -->
      <div class="w3-card-2 w3-margin w3-margin-top">
        <%= image_tag("img4.jpg", :alt => "rss feed" , size: "434x434" , :style => "padding-top: 20px;
    padding-right: 50px;
    padding-bottom: 20px;
    padding-left: 20px;") %>
        <div class="w3-container w3-white">
          <h4><b>About Aditya</b></h4>
          <p>Just me, myself and I, exploring the universe of uknownment. I have a heart of love and good food is my kryptonite. I want to share my world with you.</p>
        </div>
      </div><hr>

      <!-- Posts -->
      <div class="w3-card-2 w3-margin">
        <div class="w3-container w3-padding">
          <h4>Popular Posts</h4>
        </div>
        <ul class="w3-ul w3-hoverable w3-white">
          <li class="w3-padding-16">
            <%= image_tag("momo.jpg", :alt => "rss feed" , size: "80x80" ) %>
            <span class="w3-large">Momo Festival</span><br>
            <span>MOmos from around delhi</span>
          </li>
          <li class="w3-padding-16">
            <%= image_tag("travel.jpg", :alt => "rss feed" , size: "80x80" ) %>
            <span class="w3-large">Wanderlust</span><br>
            <span>Love for travel</span>
          </li>
          <li class="w3-padding-16">
            <%= image_tag("dragon.jpg", :alt => "rss feed" , size: "80x80" ) %>
            <span class="w3-large">Games of Thrones</span><br>
            <span>Season 7 Coming Soon!!</span>
          </li>
          <li class="w3-padding-16 w3-hide-medium w3-hide-small">
            <%= image_tag("img2.jpg", :alt => "rss feed" , size: "80x80" ) %>
            <span class="w3-large">Fashion Trending</span><br>
            <span>Casual Shirts and Denims</span>
          </li>
        </ul>
      </div>
      <hr>

      <!-- Labels / tags -->
      <div class="w3-card-2 w3-margin">
        <div class="w3-container w3-padding">
          <h4>Tags</h4>
        </div>
        <div class="w3-container w3-white">
          <p><span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">New Delhi</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Gurgaon</span>
            <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Pantloons</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Noida</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">DIY</span>
            <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Baby</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Family</span>
            <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">News</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Clothing</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Shopping</span>
            <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Sports</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Games</span>
          </p>
        </div>
      </div>

      <!-- END Introduction Menu -->
    </div>

    <!-- END GRID -->
  </div><br>

  <!-- END w3-content -->
</div>



<!-- Footer -->
<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">
  <button class="w3-button w3-black w3-disabled w3-padding-large w3-margin-bottom">Previous</button>
  <button class="w3-button w3-black w3-padding-large w3-margin-bottom">Next »</button>
  <p>   <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">  </a></p>
</footer>

</body>

<script>
    $("#card").flip({
        axis: 'y',
        trigger: 'hover'
    });
    $("#c1").flip({
        axis: 'y',
        trigger: 'hover'
    });
</script>






</html>

app/views/welcome/show.html.erb
<div class="w3-card-4 w3-margin w3-white">
  <div class="w3-margin-left">
    <br>
    <p>
      <strong>Title:</strong>
      <%= @article.title %>
    </p>

    <p>
      <strong>Text:</strong>
      <%= @article.text %>
    </p>
  </div>





  <%= link_to 'Back', root_path %>
</div>